spring:
  application:
    name: ms-address
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
service-clients:
  cep:
    url: https://viacep.com.br
  state:
    url: https://servicodados.ibge.gov.br/api
